### ISSUE TITLE
How do I perform multiple shell provisioning with this setup?

### ISSUE THREAD

**Issue by jgonyea** [bfolliot/vagrant-yml#1]
When I attempt to call multiple shell scripts, it only seems to use the last one:

``` yaml
    provision:
      shell:
        :path: "bootstrapScripts/CentOS/CentOS_LAMP-FTP.sh"
      shell:
        :path: "bootstrapScripts/Web/cleanDrupalInstall.sh"
```

Thanks in advance.
