### ISSUE TITLE
Port Forward options

### ISSUE THREAD

**Issue by jgonyea** [bfolliot/vagrant-yml#2]
Would you consider adding support for port forwards from the yaml config file?

Maybe something akin to this?:

``` yml
portforward:
  forward1:
    host: 8080
    guest: 80
  forward2:
    host: 8081
    guest: 443
```

Thanks in advance either way.
